# Generated by Django 2.2.12 on 2020-05-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bills',
            name='nit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clients',
            name='document',
            field=models.IntegerField(),
        ),
    ]
