# Generated by Django 2.2.12 on 2020-05-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_auto_20200511_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='contra',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
