# Generated by Django 2.2.12 on 2020-05-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_clients_contra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.clients'),
        ),
    ]
